### ISSUE TITLE
Escaping current game results prevents subsequent gameplay

### ISSUE THREAD

**Issue by ghost** [Schwenke/letterflash#2]
Using the keyboard `esc` key to close the current game results prevents further gameplay.

Reproduction steps:
1. win game
2. esc key to view board
3. options > "New game"
4. Type in word and use keyboard enter
5. "You cannot enter empty words" warning displays and options menu opens instead of word being entered.

Firefox 96.0.3 / Windows
5-word length, hard and normal modes, dark mode enabled.

**Comment by Schwenke** [comment]
Thanks for reporting this. Should be fixed now.

**Comment by ghost** [comment]
Working for me now, thanks!
