### ISSUE TITLE
"Time Spent" value wrong after closing tab mid-game.

### ISSUE THREAD

**Issue by ghost** [Schwenke/letterflash#23]
This is easier to reproduce when you know the word: https://www.letterflash.com/?share=TU9MQVI (MOLAR)

It might also be dependent on using the "pick up where i left off"-type browser feature.

Reproduction steps: (Firefox Desktop)
1. begin solving & note time 
2. close browser & wait a minute or so
3. reopen browser and finish solving
4. Results modal shows "Time Spent" value since after reopening the tab, not since starting the round

**Comment by Schwenke** [comment]
This has been added and works like so:


Game time is now stored in the session.

The game timer will only tick if the game is set as the current browser tab and the user has made at least one guess.

The game will auto-update the session every 30 seconds if the above conditions are true.

If the game is over (win or lose), the timer will not tick and the game will not auto-update the session.
