### ISSUE TITLE
Hard mode 

### ISSUE THREAD

**Issue by asmallshocktopus** [Schwenke/letterflash#25]
I can't turn off hard mode and it's ruining my life

**Comment by Schwenke** [comment]
Hey, just now seeing this.

There was a change recently where hard mode is now disabled until you "finish" a game - that is, no guesses are made or the game is in the "game over state" where the results screen is displayed. You should be able to change it then. Let me know if you still have problems.

**Comment by asmallshocktopus** [comment]
I was high AF and should have realized that. Sorry. 😳

**Comment by Schwenke** [comment]
🤣 all good. I'll consider it closed!
