### ISSUE TITLE
Allow failure state to also have a copy to clipboard action

### ISSUE THREAD

**Issue by Schwenke** [Schwenke/letterflash#6]
Currently, when you fail a word, you are presented the result prompt but with no ability to copy and paste your result.

Sometimes people like to share their losses, if only to show how hard the word was.

See if we can add a copy to clipboard for failure, which includes the secret word and all guesses made.

**Comment by kevinosborn31** [comment]
Hey @Schwenke 

I'm happy to do this, and have created the function as well as attached a button to it. What exact text would you like to be copied to the clipboard? I can add the secret word and all guesses made, that's not a problem :)

**Comment by Schwenke** [comment]
Hey @kevinosborn31,

I would like it to be similar to the victory component copy action, except I think it would be great to do what Wordle does - maybe do an "X/6", for the guesses, where the "X" signifies it was a failure.

The bug for not recording the final guess might still need to be fixed before it looks correct, but I won't push an update until everything is in, so no reason this can't be fixed in the mean time.

**Comment by Schwenke** [comment]
I am going to go ahead and get this patched since I want to push an update tonight.

Thanks for the interest Kevin! Ill post more issues in the future once I get more feedback.

**Comment by Schwenke** [comment]
Completed.
