### ISSUE TITLE
Add a .favicon

### ISSUE THREAD

**Issue by Schwenke** [Schwenke/letterflash#7]
Letter flash currently uses the default Angular favicon, which is just the little A inside the shield.

Use an actual favicon for the game instead.

**Comment by adkood** [comment]
please assign it to me.

**Comment by Schwenke** [comment]
Hey @adkood , if you still want to work on this.

You can use [this site](https://www.favicon.cc/) to create one. I am thinking with an "L" or "LF", keep it simple.

Let me know if you are up to do that - I'll want to review it first.

**Comment by Schwenke** [comment]
I'll work on this since I got some time - I appreciate the offer though.
