### ISSUE TITLE
6th guess not recorded in history

### ISSUE THREAD

**Issue by ghost** [Schwenke/letterflash#8]
Game history only records the first 5 out of 6 word guesses. For winning games it isn't an issue but for losing games the last guess is lost.

Steps to reproduce:
1. Lose a game
2. Settings > History
3. "Guesses" column only contains 5 guesses instead of 6

**Comment by Schwenke** [comment]
This has been addressed - the final guess will now always be recorded in both victory and failure scenarios to be consistent.

An update will be pushed to the site when more things get addressed.
